In [2]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

In [3]:
Dataset=pd.read_csv('news.csv',index_col=None)

In [4]:
Dataset.head(10)

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   
5        6903                                        Tehran, USA   
6        7341  Girl Horrified At What She Watches Boyfriend D...   
7          95                  ‘Britain’s Schindler’ Dies at 106   
8        4869  Fact check: Trump and Clinton at the 'commande...   
9        2909  Iran reportedly makes new push for uranium con...   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL  
5    \nI’m not an immigrant, but my grandparents ...  FAKE  
6  Share This Baylee Luciani (left), Screenshot o...  FAKE  
7  A Czech stockbroker who saved more than 650 Je...  REAL  
8  Hillary Clinton and Donald Trump made some ina...  REAL  
9  Iranian negotiators reportedly have made a las...  REAL

In [5]:
Dataset=Dataset.drop("Unnamed: 0",axis=1)

In [6]:
Dataset.head(10)

title  \
0                       You Can Smell Hillary’s Fear   
1  Watch The Exact Moment Paul Ryan Committed Pol...   
2        Kerry to go to Paris in gesture of sympathy   
3  Bernie supporters on Twitter erupt in anger ag...   
4   The Battle of New York: Why This Primary Matters   
5                                        Tehran, USA   
6  Girl Horrified At What She Watches Boyfriend D...   
7                  ‘Britain’s Schindler’ Dies at 106   
8  Fact check: Trump and Clinton at the 'commande...   
9  Iran reportedly makes new push for uranium con...   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL  
5    \nI’m not an immigrant, but my grandparents ...  FAKE  
6  Share This Baylee Luciani (left), Screenshot o...  FAKE  
7  A Czech stockbroker who saved more than 650 Je...  REAL  
8  Hillary Clinton and Donald Trump made some ina...  REAL  
9  Iranian negotiators reportedly have made a las...  REAL

In [7]:
y=Dataset["label"]

In [8]:
X_train,X_test,Y_train,Y_test=train_test_split(Dataset["text"],y,test_size=0.30,random_state=53)

In [16]:
count_vectorizer = CountVectorizer(stop_words='english')
count_train = count_vectorizer.fit_transform(X_train)
print(count_train)
count_test = count_vectorizer.transform(X_test)

  (0, 11291)	1
  (0, 14397)	3
  (0, 46000)	1
  (0, 29899)	1
  (0, 23666)	1
  (0, 42735)	4
  (0, 28294)	2
  (0, 46051)	1
  (0, 45333)	1
  (0, 36607)	1
  (0, 30207)	1
  (0, 19536)	3
  (0, 15302)	2
  (0, 27653)	1
  (0, 11228)	2
  (0, 8815)	2
  (0, 47576)	1
  (0, 35601)	1
  (0, 24408)	1
  (0, 10708)	4
  (0, 24349)	2
  (0, 47143)	1
  (0, 52803)	1
  (0, 16125)	2
  (0, 52745)	5
  :	:
  (4433, 54901)	1
  (4433, 35836)	1
  (4433, 53806)	1
  (4433, 51202)	1
  (4433, 13166)	1
  (4433, 11604)	1
  (4433, 56145)	1
  (4433, 36356)	1
  (4433, 42811)	1
  (4433, 7681)	1
  (4433, 3366)	1
  (4433, 43287)	1
  (4433, 48275)	1
  (4433, 42762)	1
  (4433, 7675)	1
  (4433, 22784)	1
  (4433, 7232)	1
  (4433, 50866)	1
  (4433, 39480)	1
  (4433, 17522)	1
  (4433, 50865)	1
  (4433, 11444)	1
  (4433, 53817)	1
  (4433, 21229)	1
  (4433, 8102)	1


In [10]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Gajalakshmi
[nltk_data]     G\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [17]:
len(count_vectorizer.get_feature_names_out())#length of unique count

57870

In [18]:
print(count_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [19]:
#model creation
clf=MultinomialNB()
clf.fit(count_train,Y_train)
pred=clf.predict(count_test)
score=metrics.accuracy_score(Y_test,pred)
print("accuracy: %03f" % score)
cm=metrics.confusion_matrix(Y_test,pred,labels=['FAKE','REAL'])


accuracy: 0.902157


In [20]:
from sklearn.metrics import classification_report
report=classification_report(Y_test,pred)
print(report)

              precision    recall  f1-score   support

        FAKE       0.92      0.87      0.90       913
        REAL       0.89      0.93      0.91       988

    accuracy                           0.90      1901
   macro avg       0.90      0.90      0.90      1901
weighted avg       0.90      0.90      0.90      1901



In [21]:
Dataset['text'][0]

'Daniel Greenfield, a Shillman Journalism Fellow at the Freedom Center, is a New York writer focusing on radical Islam. \nIn the final stretch of the election, Hillary Rodham Clinton has gone to war with the FBI. \nThe word “unprecedented” has been thrown around so often this election that it ought to be retired. But it’s still unprecedented for the nominee of a major political party to go war with the FBI. \nBut that’s exactly what Hillary and her people have done. Coma patients just waking up now and watching an hour of CNN from their hospital beds would assume that FBI Director James Comey is Hillary’s opponent in this election. \nThe FBI is under attack by everyone from Obama to CNN. Hillary’s people have circulated a letter attacking Comey. There are currently more media hit pieces lambasting him than targeting Trump. It wouldn’t be too surprising if the Clintons or their allies were to start running attack ads against the FBI. \nThe FBI’s leadership is being warned that the entir

In [22]:
count_train[0]

<1x57870 sparse matrix of type '<class 'numpy.int64'>'
	with 156 stored elements in Compressed Sparse Row format>

In [27]:
count_vectorizer=CountVectorizer(stop_words='english')
count_train=count_vectorizer.fit_transform(X_train)

In [29]:
X_train[[0]]

0    Daniel Greenfield, a Shillman Journalism Fello...
Name: text, dtype: object

In [32]:
X_train[[5]]

5      \nI’m not an immigrant, but my grandparents ...
Name: text, dtype: object

In [31]:
clf.predict(count_train[[5]])

array(['REAL'], dtype='<U4')